version: "3"


services:
  app:
    image: wefoxgroup/wg-web-challenge:latest
    container_name: wg-web-challenge
    ports:
      - 3000:3000
  web:
    image: wefox1
    container_name: web-ui
    ports:
      - 8080:8080
